Update packages in kitchen_terraform/Dockerfile
This fixes the following build issue:
```
ERROR: unsatisfiable constraints:
  ca-certificates-20171114-r3:
    breaks: world[ca-certificates=20161130-r0]
    satisfies: curl-7.61.1-r1[ca-certificates]
               libcurl-7.61.1-r1[ca-certificates]
               .ruby-rundeps-0[ca-certificates]
  bash-4.4.19-r1:
    breaks: world[bash=4.3.42-r5]
  curl-7.61.1-r1:
    breaks: world[curl=7.60.0-r1]
  musl-dev-1.1.19-r10:
    breaks: world[musl-dev=1.1.14-r16]
    satisfies: libc-dev-0.7.1-r0[musl-dev]
  g++-6.4.0-r9:
    breaks: world[g++=5.3.0-r0]
  git-2.18.1-r0:
    breaks: world[git=2.8.6-r0]
  jq-1.6_rc1-r1:
    breaks: world[jq=1.5-r2]
  make-4.2.1-r2:
    breaks: world[make=4.1-r1]
  python2-2.7.15-r1:
    breaks: world[python=2.7.14-r0]
    satisfies:
               python2-dev-2.7.15-r1[python2=2.7.15-r1]
               py-setuptools-39.1.0-r0[python2]
               py2-pip-10.0.1-r0[python2]
  py2-pip-10.0.1-r0:
    breaks: world[py-pip=8.1.2-r0]
  python2-dev-2.7.15-r1:
    breaks: world[python-dev=2.7.14-r0]
```